default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: hello-app
  username: root
  password: 123456789
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: sample-app
test:
  <<: *default
  database: sample-app